# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr
  - testthat
r_github_packages:
  - mrc-ide/odin
after_success:
  - Rscript -e 'library(covr); codecov()'
notifications:
  email: false
  slack: dideimperial:FGpKA1qdJd5D1zicaPrqH0Wj

