// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// demog_test
std::vector<int> demog_test(int N, int days, int substep, std::vector<double> age_distribution, std::vector<double> life_distribution);
RcppExport SEXP _siR_demog_test(SEXP NSEXP, SEXP daysSEXP, SEXP substepSEXP, SEXP age_distributionSEXP, SEXP life_distributionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type days(daysSEXP);
    Rcpp::traits::input_parameter< int >::type substep(substepSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type age_distribution(age_distributionSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type life_distribution(life_distributionSEXP);
    rcpp_result_gen = Rcpp::wrap(demog_test(N, days, substep, age_distribution, life_distribution));
    return rcpp_result_gen;
END_RCPP
}
// weighted_sample
unsigned int weighted_sample(std::vector<double>& weights, unsigned int istart);
RcppExport SEXP _siR_weighted_sample(SEXP weightsSEXP, SEXP istartSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type istart(istartSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_sample(weights, istart));
    return rcpp_result_gen;
END_RCPP
}
// seq_cpp
std::vector<double> seq_cpp(double from, double to, double by);
RcppExport SEXP _siR_seq_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP bySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type from(fromSEXP);
    Rcpp::traits::input_parameter< double >::type to(toSEXP);
    Rcpp::traits::input_parameter< double >::type by(bySEXP);
    rcpp_result_gen = Rcpp::wrap(seq_cpp(from, to, by));
    return rcpp_result_gen;
END_RCPP
}
// exp1
double exp1(double x);
RcppExport SEXP _siR_exp1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(exp1(x));
    return rcpp_result_gen;
END_RCPP
}
// ibm_closed_sir_rcpp
Rcpp::List ibm_closed_sir_rcpp(double sigma, double beta, int N, int i0, int t_final, double dt);
RcppExport SEXP _siR_ibm_closed_sir_rcpp(SEXP sigmaSEXP, SEXP betaSEXP, SEXP NSEXP, SEXP i0SEXP, SEXP t_finalSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type i0(i0SEXP);
    Rcpp::traits::input_parameter< int >::type t_final(t_finalSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    rcpp_result_gen = Rcpp::wrap(ibm_closed_sir_rcpp(sigma, beta, N, i0, t_final, dt));
    return rcpp_result_gen;
END_RCPP
}
// ibm_het
Rcpp::List ibm_het(double sigma, double beta, int N, int i0, Rcpp::NumericVector times, double dt, bool het);
RcppExport SEXP _siR_ibm_het(SEXP sigmaSEXP, SEXP betaSEXP, SEXP NSEXP, SEXP i0SEXP, SEXP timesSEXP, SEXP dtSEXP, SEXP hetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type i0(i0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< bool >::type het(hetSEXP);
    rcpp_result_gen = Rcpp::wrap(ibm_het(sigma, beta, N, i0, times, dt, het));
    return rcpp_result_gen;
END_RCPP
}
// ibm_scheduled
Rcpp::List ibm_scheduled(double sigma, double beta, int N, int i0, int days, int substep, std::vector<double> age_distribution, std::vector<double> life_distribution);
RcppExport SEXP _siR_ibm_scheduled(SEXP sigmaSEXP, SEXP betaSEXP, SEXP NSEXP, SEXP i0SEXP, SEXP daysSEXP, SEXP substepSEXP, SEXP age_distributionSEXP, SEXP life_distributionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type i0(i0SEXP);
    Rcpp::traits::input_parameter< int >::type days(daysSEXP);
    Rcpp::traits::input_parameter< int >::type substep(substepSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type age_distribution(age_distributionSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type life_distribution(life_distributionSEXP);
    rcpp_result_gen = Rcpp::wrap(ibm_scheduled(sigma, beta, N, i0, days, substep, age_distribution, life_distribution));
    return rcpp_result_gen;
END_RCPP
}
// steps
int steps(int& days, int& substep);
RcppExport SEXP _siR_steps(SEXP daysSEXP, SEXP substepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int& >::type days(daysSEXP);
    Rcpp::traits::input_parameter< int& >::type substep(substepSEXP);
    rcpp_result_gen = Rcpp::wrap(steps(days, substep));
    return rcpp_result_gen;
END_RCPP
}
// years_to_steps
int years_to_steps(int& years, int& substep);
RcppExport SEXP _siR_years_to_steps(SEXP yearsSEXP, SEXP substepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int& >::type years(yearsSEXP);
    Rcpp::traits::input_parameter< int& >::type substep(substepSEXP);
    rcpp_result_gen = Rcpp::wrap(years_to_steps(years, substep));
    return rcpp_result_gen;
END_RCPP
}
// days_to_steps
int days_to_steps(int& days, int& substep);
RcppExport SEXP _siR_days_to_steps(SEXP daysSEXP, SEXP substepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int& >::type days(daysSEXP);
    Rcpp::traits::input_parameter< int& >::type substep(substepSEXP);
    rcpp_result_gen = Rcpp::wrap(days_to_steps(days, substep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_siR_demog_test", (DL_FUNC) &_siR_demog_test, 5},
    {"_siR_weighted_sample", (DL_FUNC) &_siR_weighted_sample, 2},
    {"_siR_seq_cpp", (DL_FUNC) &_siR_seq_cpp, 3},
    {"_siR_exp1", (DL_FUNC) &_siR_exp1, 1},
    {"_siR_ibm_closed_sir_rcpp", (DL_FUNC) &_siR_ibm_closed_sir_rcpp, 6},
    {"_siR_ibm_het", (DL_FUNC) &_siR_ibm_het, 7},
    {"_siR_ibm_scheduled", (DL_FUNC) &_siR_ibm_scheduled, 8},
    {"_siR_steps", (DL_FUNC) &_siR_steps, 2},
    {"_siR_years_to_steps", (DL_FUNC) &_siR_years_to_steps, 2},
    {"_siR_days_to_steps", (DL_FUNC) &_siR_days_to_steps, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_siR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
