# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
demog_test <- function(N, days, substep, age_distribution, life_distribution) {
    .Call('_siR_demog_test', PACKAGE = 'siR', N, days, substep, age_distribution, life_distribution)
}

#' @export
weighted_sample <- function(weights, istart) {
    .Call('_siR_weighted_sample', PACKAGE = 'siR', weights, istart)
}

#' @export
seq_cpp <- function(from, to, by) {
    .Call('_siR_seq_cpp', PACKAGE = 'siR', from, to, by)
}

#' ibm_closed_sir_rcpp 1
#'
#' @inheritParams ibm_closed_sir
#'
#' @return IBM model output
#' @export
ibm_closed_sir_rcpp <- function(sigma = 2, beta = 4, N = 1000L, i0 = 1L, t_final = 100L, dt = 0.01) {
    .Call('_siR_ibm_closed_sir_rcpp', PACKAGE = 'siR', sigma, beta, N, i0, t_final, dt)
}

#' @export
ibm_het <- function(sigma, beta, N, i0, times, dt, het, age_distribution, life_distribution) {
    .Call('_siR_ibm_het', PACKAGE = 'siR', sigma, beta, N, i0, times, dt, het, age_distribution, life_distribution)
}

#' @export
ibm_scheduled <- function(sigma, beta, N, i0, days, substep, age_distribution, life_distribution) {
    .Call('_siR_ibm_scheduled', PACKAGE = 'siR', sigma, beta, N, i0, days, substep, age_distribution, life_distribution)
}

#' @export
steps <- function(days, substep) {
    .Call('_siR_steps', PACKAGE = 'siR', days, substep)
}

#' @export
years_to_steps <- function(years, substep) {
    .Call('_siR_years_to_steps', PACKAGE = 'siR', years, substep)
}

#' @export
days_to_steps <- function(days, substep) {
    .Call('_siR_days_to_steps', PACKAGE = 'siR', days, substep)
}

