# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
demog_test <- function(N, agedist, time) {
    invisible(.Call('_siR_demog_test', PACKAGE = 'siR', N, agedist, time))
}

#' @export
weighted_sample <- function(weights) {
    .Call('_siR_weighted_sample', PACKAGE = 'siR', weights)
}

#' @export
seq_cpp <- function(from, to, by) {
    .Call('_siR_seq_cpp', PACKAGE = 'siR', from, to, by)
}

#' ibm_closed_sir_rcpp 1
#'
#' @inheritParams ibm_closed_sir
#'
#' @return IBM model output
#' @export
ibm_closed_sir_rcpp <- function(sigma = 2, beta = 4, N = 1000L, i0 = 1L, t_final = 100L, dt = 0.01) {
    .Call('_siR_ibm_closed_sir_rcpp', PACKAGE = 'siR', sigma, beta, N, i0, t_final, dt)
}

#' @export
ibm_het <- function(sigma = 2, beta = 4, N = 1000L, i0 = 1L, times = 0L, dt = 0.1, het = FALSE) {
    .Call('_siR_ibm_het', PACKAGE = 'siR', sigma, beta, N, i0, times, dt, het)
}

